spring:
  security:
    user:
      name: admin
      password: admin
      roles: ROLE_ADMIN
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format-sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dvo_db
    username: postgres
    password: postgres
    hikari:
      schema: hb_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hb_schema
      connection-timeout: 10000
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/booking_db?authSource=admin
app:
  security:
    type: db
  kafka:
    kafkaUserTopic: "user-topic"
    kafkaBookingTopic: "booking-topic"
    kafkaGroupId: "group-id"